// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/torrentd.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentRequest) Reset() {
	*x = AddTorrentRequest{}
	mi := &file_proto_torrentd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentRequest) ProtoMessage() {}

func (x *AddTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrentd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentRequest.ProtoReflect.Descriptor instead.
func (*AddTorrentRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrentd_proto_rawDescGZIP(), []int{0}
}

func (x *AddTorrentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AddTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentResponse) Reset() {
	*x = AddTorrentResponse{}
	mi := &file_proto_torrentd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentResponse) ProtoMessage() {}

func (x *AddTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrentd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentResponse.ProtoReflect.Descriptor instead.
func (*AddTorrentResponse) Descriptor() ([]byte, []int) {
	return file_proto_torrentd_proto_rawDescGZIP(), []int{1}
}

func (x *AddTorrentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTorrentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentsRequest) Reset() {
	*x = ListTorrentsRequest{}
	mi := &file_proto_torrentd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentsRequest) ProtoMessage() {}

func (x *ListTorrentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrentd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentsRequest.ProtoReflect.Descriptor instead.
func (*ListTorrentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrentd_proto_rawDescGZIP(), []int{2}
}

type ListTorrentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*TorrentInfo         `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTorrentsResponse) Reset() {
	*x = ListTorrentsResponse{}
	mi := &file_proto_torrentd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTorrentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTorrentsResponse) ProtoMessage() {}

func (x *ListTorrentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrentd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTorrentsResponse.ProtoReflect.Descriptor instead.
func (*ListTorrentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_torrentd_proto_rawDescGZIP(), []int{3}
}

func (x *ListTorrentsResponse) GetTorrents() []*TorrentInfo {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type WatchProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressRequest) Reset() {
	*x = WatchProgressRequest{}
	mi := &file_proto_torrentd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressRequest) ProtoMessage() {}

func (x *WatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrentd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrentd_proto_rawDescGZIP(), []int{4}
}

func (x *WatchProgressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TorrentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Downloaded    int32                  `protobuf:"varint,3,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentInfo) Reset() {
	*x = TorrentInfo{}
	mi := &file_proto_torrentd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentInfo) ProtoMessage() {}

func (x *TorrentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrentd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentInfo.ProtoReflect.Descriptor instead.
func (*TorrentInfo) Descriptor() ([]byte, []int) {
	return file_proto_torrentd_proto_rawDescGZIP(), []int{5}
}

func (x *TorrentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentInfo) GetDownloaded() int32 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *TorrentInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TorrentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_torrentd_proto protoreflect.FileDescriptor

const file_proto_torrentd_proto_rawDesc = "" +
	"\n" +
	"\x14proto/torrentd.proto\x12\btorrentd\"'\n" +
	"\x11AddTorrentRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"$\n" +
	"\x12AddTorrentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListTorrentsRequest\"I\n" +
	"\x14ListTorrentsResponse\x121\n" +
	"\btorrents\x18\x01 \x03(\v2\x15.torrentd.TorrentInfoR\btorrents\"&\n" +
	"\x14WatchProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x7f\n" +
	"\vTorrentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x03 \x01(\x05R\n" +
	"downloaded\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xec\x01\n" +
	"\bTorrentd\x12G\n" +
	"\n" +
	"AddTorrent\x12\x1b.torrentd.AddTorrentRequest\x1a\x1c.torrentd.AddTorrentResponse\x12M\n" +
	"\fListTorrents\x12\x1d.torrentd.ListTorrentsRequest\x1a\x1e.torrentd.ListTorrentsResponse\x12H\n" +
	"\rWatchProgress\x12\x1e.torrentd.WatchProgressRequest\x1a\x15.torrentd.TorrentInfo0\x01B\x12Z\x10internal/rpc;rpcb\x06proto3"

var (
	file_proto_torrentd_proto_rawDescOnce sync.Once
	file_proto_torrentd_proto_rawDescData []byte
)

func file_proto_torrentd_proto_rawDescGZIP() []byte {
	file_proto_torrentd_proto_rawDescOnce.Do(func() {
		file_proto_torrentd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_torrentd_proto_rawDesc), len(file_proto_torrentd_proto_rawDesc)))
	})
	return file_proto_torrentd_proto_rawDescData
}

var file_proto_torrentd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_torrentd_proto_goTypes = []any{
	(*AddTorrentRequest)(nil),    // 0: torrentd.AddTorrentRequest
	(*AddTorrentResponse)(nil),   // 1: torrentd.AddTorrentResponse
	(*ListTorrentsRequest)(nil),  // 2: torrentd.ListTorrentsRequest
	(*ListTorrentsResponse)(nil), // 3: torrentd.ListTorrentsResponse
	(*WatchProgressRequest)(nil), // 4: torrentd.WatchProgressRequest
	(*TorrentInfo)(nil),          // 5: torrentd.TorrentInfo
}
var file_proto_torrentd_proto_depIdxs = []int32{
	5, // 0: torrentd.ListTorrentsResponse.torrents:type_name -> torrentd.TorrentInfo
	0, // 1: torrentd.Torrentd.AddTorrent:input_type -> torrentd.AddTorrentRequest
	2, // 2: torrentd.Torrentd.ListTorrents:input_type -> torrentd.ListTorrentsRequest
	4, // 3: torrentd.Torrentd.WatchProgress:input_type -> torrentd.WatchProgressRequest
	1, // 4: torrentd.Torrentd.AddTorrent:output_type -> torrentd.AddTorrentResponse
	3, // 5: torrentd.Torrentd.ListTorrents:output_type -> torrentd.ListTorrentsResponse
	5, // 6: torrentd.Torrentd.WatchProgress:output_type -> torrentd.TorrentInfo
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_torrentd_proto_init() }
func file_proto_torrentd_proto_init() {
	if File_proto_torrentd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_torrentd_proto_rawDesc), len(file_proto_torrentd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_torrentd_proto_goTypes,
		DependencyIndexes: file_proto_torrentd_proto_depIdxs,
		MessageInfos:      file_proto_torrentd_proto_msgTypes,
	}.Build()
	File_proto_torrentd_proto = out.File
	file_proto_torrentd_proto_goTypes = nil
	file_proto_torrentd_proto_depIdxs = nil
}
