// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/torrentd.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Torrentd_AddTorrent_FullMethodName    = "/torrentd.Torrentd/AddTorrent"
	Torrentd_ListTorrents_FullMethodName  = "/torrentd.Torrentd/ListTorrents"
	Torrentd_WatchProgress_FullMethodName = "/torrentd.Torrentd/WatchProgress"
)

// TorrentdClient is the client API for Torrentd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TorrentdClient interface {
	AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error)
	ListTorrents(ctx context.Context, in *ListTorrentsRequest, opts ...grpc.CallOption) (*ListTorrentsResponse, error)
	WatchProgress(ctx context.Context, in *WatchProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TorrentInfo], error)
}

type torrentdClient struct {
	cc grpc.ClientConnInterface
}

func NewTorrentdClient(cc grpc.ClientConnInterface) TorrentdClient {
	return &torrentdClient{cc}
}

func (c *torrentdClient) AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTorrentResponse)
	err := c.cc.Invoke(ctx, Torrentd_AddTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentdClient) ListTorrents(ctx context.Context, in *ListTorrentsRequest, opts ...grpc.CallOption) (*ListTorrentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTorrentsResponse)
	err := c.cc.Invoke(ctx, Torrentd_ListTorrents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentdClient) WatchProgress(ctx context.Context, in *WatchProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TorrentInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Torrentd_ServiceDesc.Streams[0], Torrentd_WatchProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchProgressRequest, TorrentInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Torrentd_WatchProgressClient = grpc.ServerStreamingClient[TorrentInfo]

// TorrentdServer is the server API for Torrentd service.
// All implementations must embed UnimplementedTorrentdServer
// for forward compatibility.
type TorrentdServer interface {
	AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error)
	ListTorrents(context.Context, *ListTorrentsRequest) (*ListTorrentsResponse, error)
	WatchProgress(*WatchProgressRequest, grpc.ServerStreamingServer[TorrentInfo]) error
	mustEmbedUnimplementedTorrentdServer()
}

// UnimplementedTorrentdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTorrentdServer struct{}

func (UnimplementedTorrentdServer) AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTorrent not implemented")
}
func (UnimplementedTorrentdServer) ListTorrents(context.Context, *ListTorrentsRequest) (*ListTorrentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTorrents not implemented")
}
func (UnimplementedTorrentdServer) WatchProgress(*WatchProgressRequest, grpc.ServerStreamingServer[TorrentInfo]) error {
	return status.Error(codes.Unimplemented, "method WatchProgress not implemented")
}
func (UnimplementedTorrentdServer) mustEmbedUnimplementedTorrentdServer() {}
func (UnimplementedTorrentdServer) testEmbeddedByValue()                  {}

// UnsafeTorrentdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TorrentdServer will
// result in compilation errors.
type UnsafeTorrentdServer interface {
	mustEmbedUnimplementedTorrentdServer()
}

func RegisterTorrentdServer(s grpc.ServiceRegistrar, srv TorrentdServer) {
	// If the following call panics, it indicates UnimplementedTorrentdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Torrentd_ServiceDesc, srv)
}

func _Torrentd_AddTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentdServer).AddTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Torrentd_AddTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentdServer).AddTorrent(ctx, req.(*AddTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrentd_ListTorrents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTorrentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentdServer).ListTorrents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Torrentd_ListTorrents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentdServer).ListTorrents(ctx, req.(*ListTorrentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Torrentd_WatchProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TorrentdServer).WatchProgress(m, &grpc.GenericServerStream[WatchProgressRequest, TorrentInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Torrentd_WatchProgressServer = grpc.ServerStreamingServer[TorrentInfo]

// Torrentd_ServiceDesc is the grpc.ServiceDesc for Torrentd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Torrentd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torrentd.Torrentd",
	HandlerType: (*TorrentdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTorrent",
			Handler:    _Torrentd_AddTorrent_Handler,
		},
		{
			MethodName: "ListTorrents",
			Handler:    _Torrentd_ListTorrents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchProgress",
			Handler:       _Torrentd_WatchProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/torrentd.proto",
}
